await unit('Unit A', [{ energySource: 'Electrical 480V', deviceType: 'Breaker', quantity: 1 }]);
handlePhoto({ files: [await makePhoto()] }, 'source_0'); await idle();
performSaveAndNew(); await idle();
const old = new Date(Date.now() - 3 * 86400e3).toISOString();
savedEquipment[0].savedAt = old; savedEquipment[0].updatedAt = old; saveAll(); await sleep(300);
editSaved(0); await idle();
const r = { editingBefore: editingEntry && editingEntry.equipName, savedAtBefore: old };
renderSavedPanel();
r.savedRowHasDeleteButton = !!document.querySelector('.saved-item button[onclick^="deleteSaved(0)"]');
r.savedRowShowsEditing = /EDITING/.test((document.querySelector('.saved-item') || {}).innerHTML || '');
deleteSaved(0); await sleep(400);
r.afterDelete = { savedCount: savedEquipment.length, editingEntryStill: editingEntry && editingEntry.equipName, formName: document.getElementById('equipName').value, deletePrompt: msgs[msgs.length - 1], tombstoned: Object.keys(getTombstones()).length };
let clearMsg = null; window.confirm = m => { clearMsg = String(m); return false; }; clearForm(true);
r.clearPromptShown = clearMsg;
window.confirm = m => true;
performSaveAndNew(); await idle();
r.afterResave = savedEquipment.map(e => ({ name: e.equipName, savedAt: e.savedAt, exportState: entryExportState(e) }));
r.tombstonesAfter = Object.keys(getTombstones()).length;
r.toasts = toasts.slice(-4);
return r;
